name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]        # Trigger on push to main branch
  pull_request:
    branches: [ "main" ]        # Trigger on pull request to main branch 

jobs:
  build-test:
    runs-on: ubuntu-latest      # Runs on the latest Ubuntu environment 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Checks out the code from the repository

    - name: Set up Node.js
      uses: actions/setup-node@v3   # Sets up Node.js environment
      with:
        node-version: 18          # Sets Node.js version to 18

    - name: Install dependencies
      run: npm install           # Installs project dependencies via npm
      
    - name: Give execute permission to Jest binary
      run: chmod +x node_modules/.bin/jest

    - name: Run tests
      run: npm test              # Runs tests using Jest

  docker-build-push:
    needs: build-test           # Waits for the build-test job to complete successfully
    runs-on: ubuntu-latest      # Runs on the latest Ubuntu environment

    steps:
    - uses: actions/checkout@v3
    name: Check out code
 
  name: Build & push Docker image
  with:
      image: repo/image
      tags: v1, latest
      registry: registry-url.io
      dockerfile: Dockerfile.ci
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5    # Builds and pushes the Docker image
      with:
        context: .                           # Use the current directory as the context
        push: true                           # Push the image to Docker Hub
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/calculator-webapp:latest  # Tagging the image with the username and latest tag
